// Generated by scripts/generate_lpc_manifest.py. Do not edit by hand.
export const LPC_ASSET_STANDARD = "earthfolk-lpc-v1" as const;
export const LPC_WORLD_ASSETS = {
  "bed": { width: 2, height: 2, solid: true, category: "furniture" },
  "bookshelf": { width: 3, height: 2, solid: true, category: "furniture" },
  "chair": { width: 1, height: 1, solid: true, category: "furniture" },
  "cobblestone_road": { width: 3, height: 1, solid: false, category: "terrain" },
  "crop_stage_1": { width: 1, height: 1, solid: false, category: "farming" },
  "crop_stage_2": { width: 1, height: 1, solid: false, category: "farming" },
  "desk": { width: 3, height: 2, solid: true, category: "furniture" },
  "dirt_path": { width: 3, height: 1, solid: false, category: "terrain" },
  "fireplace": { width: 2, height: 3, solid: true, category: "furniture" },
  "fountain": { width: 2, height: 2, solid: true, category: "park" },
  "grass": { width: 3, height: 1, solid: false, category: "terrain" },
  "harvest_crate": { width: 1, height: 1, solid: true, category: "farming" },
  "native_tree": { width: 3, height: 3, solid: true, category: "park" },
  "plowed_dirt": { width: 1, height: 1, solid: false, category: "farming" },
  "roof_tile": { width: 3, height: 3, solid: true, category: "architecture" },
  "sand": { width: 3, height: 1, solid: false, category: "terrain" },
  "seed_plot": { width: 1, height: 1, solid: false, category: "farming" },
  "signpost": { width: 1, height: 1, solid: true, category: "park" },
  "stairs": { width: 2, height: 2, solid: false, category: "architecture" },
  "stone_wall": { width: 3, height: 3, solid: true, category: "architecture" },
  "streetlamp": { width: 1, height: 1, solid: true, category: "park" },
  "timber_trunk": { width: 3, height: 3, solid: true, category: "park" },
  "water": { width: 2, height: 2, solid: true, category: "terrain" },
  "water_barrel": { width: 1, height: 1, solid: true, category: "farming" },
  "window": { width: 1, height: 2, solid: true, category: "architecture" },
  "wood_door": { width: 1, height: 2, solid: true, category: "architecture" },
  "wood_wall": { width: 3, height: 3, solid: true, category: "architecture" },
  "wooden_bench": { width: 2, height: 1, solid: true, category: "park" },
  "wooden_bridge": { width: 3, height: 2, solid: false, category: "architecture" },
  "wooden_fence": { width: 1, height: 1, solid: true, category: "park" },
} as const;
export const LPC_STRUCTURE_TYPES = ["community_garden", "cottage", "farm_plot", "park", "road_segment", "workshop", "industrial_structure"] as const;
export type LpcWorldAssetId = keyof typeof LPC_WORLD_ASSETS;
export type LpcStructureType = typeof LPC_STRUCTURE_TYPES[number];
